import "./globals.css";
import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import clsx from "clsx";
import { TopNavbar } from "@/ui/molecules/TopNavbar";

const inter = Manrope({ subsets: ["latin", "latin-ext"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={clsx(inter.className, "flex h-screen flex-col")}>
				<TopNavbar />
				<div className="flex-grow">{children}</div>
				<footer>
					<p className="text-center text-sm text-gray-500">&copy; 2023</p>
				</footer>
			</body>
		</html>
	);
}
