import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ActiveLink } from "@/ui/atoms/ActiveLink";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<nav>
					<ul className="mt-2 flex justify-center gap-2">
						<li>
							<ActiveLink href="/" exact activeClassName="underline">
								Home
							</ActiveLink>
						</li>
						<li>
							<ActiveLink href="/products" activeClassName="underline">
								All
							</ActiveLink>
						</li>
					</ul>
				</nav>
				{children}
				<footer>
					<p className="text-center text-sm text-gray-500">&copy; 2023</p>
				</footer>
			</body>
		</html>
	);
}
